[package]
name = "advent_of_code2024"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
itertools = "0.13.0"
pathdiff = "0.2.3"
rayon = "1.10.0"
regex = "1.11.1"

[[bin]]
name = "generate"
path = "bin/generate/main.rs"

[profile.test]
inherits = "release"
